### ISSUE TITLE
Error: ENOENT

### ISSUE THREAD

**Issue by Simnepal** [derekhe/msfs2020-google-map-electron#17]
After clicking inject google map, I get an error.  Anitivirus is off and run as Admin.  MSFS not started

![google map for msfs error](https://user-images.githubusercontent.com/97015489/147905492-1b8bed2b-d86f-4efa-8250-b349949f9597.JPG)

**Comment by derekhe** [comment]
Can you find this file?
Perhaps your windows is not installed in C:?

**Comment by derekhe** [comment]
If you in C:, please check if the file exists there. If no, please add one.
Please also reference to: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#host-related-issue

**Comment by Simnepal** [comment]
yes that worked thanks
